<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Potato ORM Test Suite" tests="18" assertions="15" failures="0" errors="2" time="2.570812">
    <testsuite name="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" tests="7" assertions="5" failures="0" errors="1" time="2.255319">
      <testcase name="testSave" class="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" line="35" assertions="1" time="1.810799"/>
      <testcase name="testFind" class="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" line="46" assertions="1" time="0.409936"/>
      <testcase name="testDestroy" class="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" line="55" assertions="0" time="0.004034">
        <error type="PHPUnit_Framework_ExceptionWrapper">Laztopaz\potatoORM\Test\TestCrudOperation::testDestroy
Laztopaz\potatoORM\NoRecordDeletionException: Record deletion unsuccessful because id does not match any record

/Users/andeladev/Code/potato-ORM/src/Exceptions/NoRecordDeletionException.php:17
/Users/andeladev/Code/potato-ORM/src/Model/BaseModel.php:168
/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php:57
</error>
      </testcase>
      <testcase name="testGetAll" class="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" line="61" assertions="1" time="0.005994"/>
      <testcase name="testResultIfReturnDataIsArray" class="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" line="68" assertions="1" time="0.002929"/>
      <testcase name="testResultReturnIsEmptyArray" class="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" line="74" assertions="1" time="0.002626"/>
      <testcase name="testCheckObjectRelatedMapping" class="Laztopaz\potatoORM\Test\TestCrudOperation" file="/Users/andeladev/Code/potato-ORM/test/CrudOperationTest.php" line="81" assertions="0" time="0.019001"/>
    </testsuite>
    <testsuite name="Laztopaz\potatoORM\Test\TestDatabaseConnection" file="/Users/andeladev/Code/potato-ORM/test/DatabaseConnectionTest.php" tests="6" assertions="6" failures="0" errors="0" time="0.300339">
      <testcase name="testCreateTable" class="Laztopaz\potatoORM\Test\TestDatabaseConnection" file="/Users/andeladev/Code/potato-ORM/test/DatabaseConnectionTest.php" line="45" assertions="1" time="0.286632"/>
      <testcase name="testGetColumnNames" class="Laztopaz\potatoORM\Test\TestDatabaseConnection" file="/Users/andeladev/Code/potato-ORM/test/DatabaseConnectionTest.php" line="59" assertions="1" time="0.003457"/>
      <testcase name="testDeleteRecord" class="Laztopaz\potatoORM\Test\TestDatabaseConnection" file="/Users/andeladev/Code/potato-ORM/test/DatabaseConnectionTest.php" line="82" assertions="1" time="0.002506"/>
      <testcase name="testInsertData" class="Laztopaz\potatoORM\Test\TestDatabaseConnection" file="/Users/andeladev/Code/potato-ORM/test/DatabaseConnectionTest.php" line="98" assertions="1" time="0.002574"/>
      <testcase name="testReadAll" class="Laztopaz\potatoORM\Test\TestDatabaseConnection" file="/Users/andeladev/Code/potato-ORM/test/DatabaseConnectionTest.php" line="114" assertions="1" time="0.002530"/>
      <testcase name="testReadSingleRecord" class="Laztopaz\potatoORM\Test\TestDatabaseConnection" file="/Users/andeladev/Code/potato-ORM/test/DatabaseConnectionTest.php" line="150" assertions="1" time="0.002640"/>
    </testsuite>
    <testsuite name="Laztopaz\potatoORM\Test\ExceptionTest" file="/Users/andeladev/Code/potato-ORM/test/ExceptionTest.php" tests="5" assertions="4" failures="0" errors="1" time="0.015155">
      <testcase name="testNoArgumentPassedToFunctionException" class="Laztopaz\potatoORM\Test\ExceptionTest" file="/Users/andeladev/Code/potato-ORM/test/ExceptionTest.php" line="43" assertions="1" time="0.003119"/>
      <testcase name="testNoArgumentForDestroy" class="Laztopaz\potatoORM\Test\ExceptionTest" file="/Users/andeladev/Code/potato-ORM/test/ExceptionTest.php" line="52" assertions="1" time="0.002790"/>
      <testcase name="testNullArgumentPassedToFunction" class="Laztopaz\potatoORM\Test\ExceptionTest" file="/Users/andeladev/Code/potato-ORM/test/ExceptionTest.php" line="60" assertions="1" time="0.002847"/>
      <testcase name="testNoRecordDeletedException" class="Laztopaz\potatoORM\Test\ExceptionTest" file="/Users/andeladev/Code/potato-ORM/test/ExceptionTest.php" line="68" assertions="1" time="0.003622"/>
      <testcase name="testEmptyArrayPassedToFindAndWhere" class="Laztopaz\potatoORM\Test\ExceptionTest" file="/Users/andeladev/Code/potato-ORM/test/ExceptionTest.php" line="76" assertions="0" time="0.002777">
        <error type="PHPUnit_Framework_ExceptionWrapper">Laztopaz\potatoORM\Test\ExceptionTest::testEmptyArrayPassedToFindAndWhere
Laztopaz\potatoORM\EmptyArrayException: Array Expected: parameter passed to this function is not an array

/Users/andeladev/Code/potato-ORM/src/Exceptions/EmptyArrayException.php:17
/Users/andeladev/Code/potato-ORM/src/Database/DatabaseHandler.php:223
/Users/andeladev/Code/potato-ORM/test/ExceptionTest.php:81
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
